services:
  # The App Service
  app:
    container_name: laravel-docker
    build: .
    ports:
      - 8080:80
    env_file:
      - GeStock/.env
    volumes:
      - ./Gestock:/var/www/html
    depends_on:
      - mysql_db

  # The Database Service
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: GeStock
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  # The phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql_db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - 8081:80
    depends_on:
      - mysql_db

volumes:
  mysql_data:
